server:
  port: 5500

info:
  environment: ${spring.profiles.active}

spring:
  webflux:
    base-path: /sync/v1
  application:
    name: sync-service
  data:
    redis:
      host: localhost
      port: 6379

logging:
  file:
    name: logs/application.log
    path: logs
  level:
    '[com.sharetimer.syncservice]': DEBUG
    '[org.hibernate.tool.schema]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.orm.jdbc.bind]': TRACE

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

timer:
  web:
    owner-token-header: "X-Owner-Token"
  redis:
    expiration:
      db-index: 0
      key-prefix: "timer:end:"
    pubsub:
      target-time-updated-channel: "timer:target-time-updated"
      target-time-updated-message-type: "target-time-updated"
      timestamp-added-channel: "timer:timestamp-added"
      timestamp-added-message-type: "timestamp-added"

webclient:
  timer-api:
    url: http://localhost:5000/api/v1

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
