global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
            application: 'api-gateway'

  - job_name: 'api-service'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['api-service:5000']
        labels:
            application: 'api-service'

  - job_name: 'sync-service'
    metrics_path: '/sync/v1/actuator/prometheus'
    static_configs:
      - targets: ['sync-service:5500']
        labels:
            application: 'sync-service'

  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']
        labels:
            application: 'discovery-server'
